### ISSUE TITLE
Can't add roomate, textbox clears out and nothing gets added

### ISSUE THREAD

**Issue by rdeckj-zz** [jgoodhcg/chorechart#1]
Can't add roomate, textbox clears out and nothing gets added
![post 404](https://cloud.githubusercontent.com/assets/10466278/21294978/a0181954-c518-11e6-9d6a-ad893dd03165.PNG)

**Comment by jgoodhcg** [comment]
This might be a typo issue. Did you try the roomate email with an initial capital letter?

**Comment by rdeckj-zz** [comment]
Yes, looks like case matters. IMO the whole thing should be case insensitive.

**Comment by jgoodhcg** [comment]
https://www.lifewire.com/are-email-addresses-case-sensitive-1171111

**Comment by rdeckj-zz** [comment]
Don't agree with closing this. The protocol supports case-sensitivity but it is not enforced.

http://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive

**Comment by rdeckj** [comment]
Technically, yes the protocol supports case-insensitivity. However, i can not think of any company that does this.
