### ISSUE TITLE
Feature: Chart Context

### ISSUE THREAD

**Issue by carrierwav** [jgoodhcg/chorechart#3]
When I have multiple households, I sometimes forget which house I'm adding chores to. It would be nice to have some sort of context on the /chart page like the /roomates page already has.

**Comment by jgoodhcg** [comment]
Fixes are here https://github.com/jgoodhcg/chorechart/commit/62a5f92de665d24cbf2f110238d24d50defd2f59, will release with next alpha version. 

![image](https://cloud.githubusercontent.com/assets/10408149/21352130/1d5bd0a6-c68e-11e6-8713-0055c2241a6c.png)
